config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    unauthenticated { root to: "showcase_site#landing", as: :unauthenticated_root }
    # unauthenticated { root to: "devise/sessions#new", as: :unauthenticated_root }

    resource :profile, only: [:edit, :update], controller: :profile

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :maintenance
    end

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :admin
    end

    root "feed#show"
    resource :feed, only: [:show], controller: :feed
    resources :bottles, except: :destroy do
      member do
        patch :bookmark
      end
    end
    resources :producers, except: :destroy
    resources :producer_labels, only: [:destroy]
    resource :map, only: [:show], controller: :map
    resources :passwords, only: [:update]
  end

  get "landing", to: "showcase_site#landing"
end

app/views/sidebar/_content.html.slim
.flex-1.pt-5.pb-4.overflow-y-auto class=(media == :mobile ? "h-0" : "flex flex-col")
  .flex.items-center.flex-shrink-0.px-4
    = link_to feed_path do
      = image_tag "logo.png", class: "h-8 w-auto", alt: "logo"
  = render "sidebar/menu"
.flex-shrink-0.flex.items-center.justify-between.border-t.border-gray-500.p-4
  = link_to edit_profile_path, class: "flex-shrink-0 group block" do
    .flex.items-center
      div
        = rounded_image(current_user.photo, 40)
      .ml-3
        p.text-sm.font-medium.text-white = current_user.full_name
        p.text-xs.font-medium.text-red-200.group-hover:text-white = t(".view_profile")

  = button_to destroy_user_session_path, method: :delete do
    i.fa-solid.fa-arrow-right-from-bracket.text-white

app/views/sidebar/_desktop.html.slim
.hidden.md:flex.md:w-64.md:flex-col.md:fixed.md:inset-y-0
  .flex-1.flex.flex-col.min-h-0.bg-stone-900
    = render "sidebar/content", media: :desktop

app/views/sidebar/_menu.html.slim
nav.mt-10.flex-1.px-2.space-y-1
  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.maintenance"),
    icon: "fa-house",
    path: maintenance_path,
    policy: MaintenancePolicy.role_can_access?)

  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.admin"),
    icon: "fa-house",
    path: admin_path,
    policy: AdminPolicy.role_can_access?)

  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.users"),
    icon: "fa-user-group",
    path: admin_users_path,
    policy: AdminPolicy.role_can_access?)

  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.home"),
    icon: "fa-house",
    path: feed_path)

  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.wines"),
    icon: "fa-wine-bottle",
    path: bottles_path)

  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.add_wine"),
    icon: "fa-circle-plus",
    path: new_bottle_path)

  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.producers"),
    icon: "fa-grapes",
    path: producers_path)

  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.add_producer"),
    icon: "fa-circle-plus",
    path: new_producer_path)

  = render MenuLinkComponent::MenuLinkComponent.new(title: t("menu.explore"),
    icon: "fa-map",
    path: map_path)

app/views/sidebar/_mobile.html.slim
.relative.z-40.hidden.md:hidden role="dialog" aria-modal="true" data={ "sidebar-target": "container" }
  .fixed.inset-0.bg-stone-600.bg-opacity-75.transition-opacity[
    data={ "sidebar-target": "backdrop" }
    data-transition-enter="ease-in-out duration-500"
    data-transition-enter-start="opacity-0"
    data-transition-enter-end="opacity-100"
    data-transition-leave="ease-in-out duration-500"
    data-transition-leave-start="opacity-100"
    data-transition-leave-end="opacity-0"
  ]
  .fixed.inset-0.flex.z-40
    .relative.flex-1.flex.flex-col.max-w-xs.w-full.bg-stone-900[
      data={ "sidebar-target": "panel" }
      data-transition-enter="transform transition ease-in-out duration-500 sm:duration-700"
      data-transition-enter-start="-translate-x-full"
      data-transition-enter-end="translate-x-0"
      data-transition-leave="transform transition ease-in-out duration-500 sm:duration-700"
      data-transition-leave-start="translate-x-0"
      data-transition-leave-end="-translate-x-full"
    ]
      .absolute.top-0.right-0.-mr-12.pt-2[
        data={ "sidebar-target": "closeButton" }
        data-transition-enter="ease-in-out duration-500"
        data-transition-enter-start="opacity-0"
        data-transition-enter-end="opacity-100"
        data-transition-leave="ease-in-out duration-500"
        data-transition-leave-start="opacity-100"
        data-transition-leave-end="opacity-0"
      ]
        = button_tag type: "button",
          data: { action: "sidebar#hide" },
          class: "ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" do
          span.sr-only
            | Close sidebar
          svg.h-6.w-6.text-white[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true"]
            path[stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"]
      = render "sidebar/content", media: :mobile

    .flex-shrink-0.w-14[aria-hidden="true"]