config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    unauthenticated { root to: "showcase_site#landing", as: :unauthenticated_root }
    # unauthenticated { root to: "devise/sessions#new", as: :unauthenticated_root }

    resource :profile, only: [:edit, :update], controller: :profile

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :maintenance
    end

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :admin
    end

    root "feed#show"
    resource :feed, only: [:show], controller: :feed
    resources :bottles, except: :destroy do
      member do
        patch :bookmark
      end
    end
    resources :producers, except: :destroy
    resources :producer_labels, only: [:destroy]
    resource :map, only: [:show], controller: :map
    resources :passwords, only: [:update]
  end

  get "landing", to: "showcase_site#landing"
end

app/models/bottle.rb
# frozen_string_literal: true

class Bottle < ApplicationRecord
  include PgSearch::Model
  extend Enumerize
  acts_as_votable

  # Associations
  belongs_to :user
  belongs_to :producer, optional: true

  # to check how to use , if: :producer_id_changed?
  after_save :set_domaine_name

  COUNTRIES = %i[
    france
  ].freeze

  REGIONS = %i[
    alsace_lorraine
    beaujolais
    bordeaux
    bourgogne
    champagne
    corse
    jura_bugey_savoie
    languedoc_roussillon
    loire
    provence
    rhone
    sud_ouest
  ].freeze

  COLORS = %i[pink red yellow white].freeze

  enumerize :region, in: REGIONS, predicates: true
  enumerize :color, in: COLORS, predicates: true
  enumerize :country, in: COUNTRIES, predicates: true

  # Associations
  has_one_attached :photo

  # Validations
  validates :region, presence: true
  validates :color, presence: true

  # Scopes and search

  scope :by_color, -> (color) { where(color:) }
  scope :bookmarked_by, -> (user_id) { joins(:votes_for).where(votes: { voter_id: user_id, voter_type: "User", vote_scope: "bookmark" }) }


  pg_search_scope :search_general_information,
                  against: [:name, :domaine_name, :producer_name, :appelation, :region],
                  using: {
                    tsearch: { prefix: true }
                  }

  def bookmark!(user)
    if user.voted_up_on? self, vote_scope: "bookmark"
      unvote_by user, vote_scope: "bookmark"
    else
      upvote_by user, vote_scope: "bookmark"
    end
  end

  private

  def set_domaine_name
    return if producer_id.nil? || domaine_name.present?

    update(domaine_name: producer.domaine_name)
  end
end

app/controllers/bottles_controller.rb
# frozen_string_literal: true

class BottlesController < ApplicationController
  before_action :set_bottle, only: %i[show edit update bookmark]
  before_action :set_producers, only: %i[new edit]

  def index
    @breadcrumb_items = {
      "bottles.show.feed": feed_path
    }
    @bottles = ::Filters::BottlesFilterService.call(params:, user_id: current_user.id)
  end

  def show
    @breadcrumb_items = {
      "bottles.show.feed": feed_path,
      "bottles.show.wines": bottles_path
    }
  end

  def new
    @breadcrumb_items = {
      "bottles.new.feed": feed_path
    }
    @bottle = Bottle.new
  end

  def edit
    @breadcrumb_items = {
      "bottles.edit.feed": feed_path,
      "bottles.edit.wines": bottles_path
    }
  end

  def create
    @bottle = current_user.bottles.build(bottle_params)

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to bottle_path(@bottle) }
      else
        @producers = Producer.all
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @bottle.update(bottle_params)
    respond_to do |format|
      if @bottle.save
        format.html { redirect_to bottle_path(@bottle) }
      else
        @producers = Producer.all
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def bookmark
    @bottle.bookmark!(current_user)
    respond_to do |format|
      format.html { redirect_to bottle_path(@bottle) }
      format.turbo_stream { render turbo_stream: turbo_stream.replace("bookmark", partial: "bottles/bookmark", locals: { bottle: @bottle }) }
    end
  end

  private

  def set_bottle
    @bottle = Bottle.find(params[:id])
  end

  def set_producers
    @producers = Producer.all
  end

  def bottle_params
    params.require(:bottle).permit(
      :name, :country, :region,
      :domaine_name, :producer_name, :producer_id,
      :appelation, :color, :year,
      :photo
    )
  end
end

app/controllers/maintenance/bottles_controller.rb
# frozen_string_literal: true

module Maintenance
  class BottlesController < BaseController
    def index
      @bottles = Bottle.all
      @breadcrumb_items = {
        "maintenance.base.index.title": maintenance_path
      }
    end
  end
end

app/views/bottles/_bookmark.html.slim
= turbo_frame_tag "bookmark" do
  = button_to bookmark_bottle_path(bottle), method: :patch do
    - if current_user.voted_up_on? bottle, vote_scope: "bookmark"
      i.fas.fa-thumbs-up
    - else
      i.fa-regular.fa-bookmark

app/views/bottles/_form.html.slim
= simple_form_for @bottle do |f|
  = render FormComponent::FormComponent.new do |c|
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :country, placeholder: t("placeholders.country")
      = f.input :region, placeholder: t("placeholders.region")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :producer_id, collection: @producers, value_method: :id, label_method: :domaine_name, label: t("activerecord.attributes.bottle.domaine_name")
      = f.input :domaine_name, placeholder: t("placeholders.domaine_name_optional")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :producer_name, placeholder: t("placeholders.producer")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :appelation, placeholder: t("placeholders.appelation")
      = f.input :color, placeholder: t("placeholders.color")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :name, placeholder: t("placeholders.name")
      = f.input :year, placeholder: t("placeholders.year"), input_html: { type: "number", min: "1900", max:"#{Date.today.year}" }
    = f.file_field :photo, class: "text-input p-0", data: { controller: "image-upload", action: "change->image-upload#compressImage" }

    - if @bottle.persisted?
      - c.with_action do
        = link_to t("cancel"), bottle_path(@bottle), class: "btn"

    - c.with_action do
      = f.submit t("save"), class: "btn btn-primary"

app/views/bottles/edit.html.slim
- content_for :title do
  = t(".edit_wine")

= render "form"

app/views/bottles/index.html.slim
- content_for :title do
  = t(".wines")
.bg-white
  .mx-auto.max-w-2xl.py-8.px-4.sm:py-12.sm:px-6.lg:max-w-7xl.lg:px-8 data-controller="toggle" data-toggle-class-value="hidden"
    h2.sr-only = t(".wines")
    = form_tag bottles_path, method: :get,
                            data: { turbo_frame: "bottles", turbo_action: "advance", controller: "search", action: "input->search#submit" },
                            class: "flex justify-center mb-2" do
      .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-3
        = text_field_tag :query, params[:query], placeholder: t(".search"), class: "form-input rounded-md shadow-sm mt-1 block w-full"
        = select_tag "color", options_for_select(Bottle::COLORS.collect{ |c| [t(c), c]}), include_blank: true, class: "form-input rounded-md shadow-sm mt-1 block w-full"
        .flex.items-center.justify-center
          = check_box_tag :my_wine, true, params[:my_wine], class: "w-4 h-4 text-red-600 bg-gray-100 border-gray-300 rounded focus:ring-red-500 dark:focus:ring-red-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600 transition duration-150 ease-in-out"
          = label_tag :my_wine, t(".my_wines"), class: "ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"
          = check_box_tag :my_bookmarks, true, params[:my_bookmark], class: "ml-2 w-4 h-4 text-red-600 bg-gray-100 border-gray-300 rounded focus:ring-red-500 dark:focus:ring-red-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600 transition duration-150 ease-in-out"
          = label_tag :my_bookmarks, t(".my_bookmarks"), class: "ml-2 text-sm font-medium text-gray-900 dark:text-gray-300"
    = turbo_frame_tag "bottles", class:"grid grid-cols-1 gap-y-4 sm:grid-cols-2 sm:gap-x-6 sm:gap-y-10 lg:grid-cols-3 lg:gap-x-8" do
      - @bottles.each do |bottle|
        .flex.justify-center.p-2
          = render FeedCardComponent::FeedCardComponent.new(instance: bottle, path: bottle_path(bottle))

app/views/bottles/new.html.slim
- content_for :title do
  = t(".new_wine")

= simple_form_for @bottle, url: bottles_path do |f|
  = render FormComponent::FormComponent.new do |c|
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :country, placeholder: t("placeholders.country")
      = f.input :region, placeholder: t("placeholders.region")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :domaine_name, placeholder: t("placeholders.domaine_name")
      = f.input :producer, placeholder: t("placeholders.producer")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :appelation, placeholder: t("placeholders.appelation")
      = f.input :color, placeholder: t("placeholders.color")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :name, placeholder: t("placeholders.name")
      = f.input :year, placeholder: t("placeholders.year"), input_html: { type: 'number', min: '1900', max:"#{Date.today.year}" }
    = f.file_field :photo, class: "text-input p-0"

    - c.with_action do
      = f.submit t("save"), class: "btn btn-primary"

app/views/bottles/show.html.slim
- color = t("enumerize.bottle.color.#{@bottle.color}")
.flex.justify-center.items-center
  - bg_image = @bottle.photo.attached? ? @bottle.photo.url : "default_wine.avif"
  .flex.flex-col.justify-between.w-72.sm:w-96.h-96.bg-white.bg-center.bg-no-repeat.bg-contain.text-gray-800.shadow-md.overflow-hidden style="background-image:url('#{image_path bg_image}')"
    .flex.justify-between.items-center.ml-4.pr-8
      .bg-red-600.text-white.bg-opacity-95.shadow.px-2.py-1.flex.items-center.font-bold.text-xs.rounded
        = @bottle.appelation
      .bg-red-600.w-10.h-12.shadow.flex.flex-col-reverse.p-2.text-center.font-bold.text-white.rounded-b-full
        = render "bookmark", bottle: @bottle
    .bg-white.bg-opacity-95.shadow-md.rounded-r-xl.p-4.flex.flex-col.mr-4.mb-8
      h3.text-xl.font-bold.pb-2
        - if @bottle.producer_id
          = link_to @bottle.domaine_name, producer_path(@bottle.producer_id)
        - else
          = @bottle.domaine_name
      p.truncate.text-gray-500.text-sm
        = "#{color} #{@bottle.year}"

= render DataPresenterComponent::DataPresenterComponent.new(title: t(".info"), path: edit_bottle_path(@bottle), icon: "fa-pen-to-square") do | data |
  = data.entry "Géographie" do
    = "#{@bottle.country&.capitalize} #{t("enumerize.bottle.region.#{@bottle.region}")}"
  = data.entry "Appelation" do
    = @bottle.appelation
  = data.entry "Nom de la cuvée" do
    = @bottle.name
  = data.entry "Mis en ligne par" do
    = @bottle.user.full_name
  - if @bottle.producer_id
    = data.entry "Domaine" do
      = link_to @bottle.domaine_name, producer_path(@bottle.producer_id)