config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    unauthenticated { root to: "showcase_site#landing", as: :unauthenticated_root }
    # unauthenticated { root to: "devise/sessions#new", as: :unauthenticated_root }

    resource :profile, only: [:edit, :update], controller: :profile

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :maintenance
    end

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :admin
    end

    root "feed#show"
    resource :feed, only: [:show], controller: :feed
    resources :bottles, except: :destroy do
      member do
        patch :bookmark
      end
    end
    resources :producers, except: :destroy
    resources :producer_labels, only: [:destroy]
    resource :map, only: [:show], controller: :map
    resources :passwords, only: [:update]
  end

  get "landing", to: "showcase_site#landing"
end

app/models/producer.rb
# frozen_string_literal: true

class Producer < ApplicationRecord
  extend Enumerize

  # Associations
  belongs_to :user
  has_many :bottles, dependent: :nullify
  has_many :producer_labels, dependent: :destroy
  has_many :labels, through: :producer_labels

  geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?

  PHOTO = {
    alsace_lorraine: "region/alsace.jpg",
    beaujolais: "region/beaujolais.jpg",
    bordeaux: "region/bordeaux.jpg",
    bourgogne: "region/bourgogne.jpg",
    champagne: "region/champagne.jpg",
    corse: "region/corse.jpg",
    jura_bugey_savoie: "region/jura.jpg",
    languedoc_roussillon: "region/languedoc.jpg",
    loire: "region/loire.jpg",
    provence: "region/provence.jpg",
    rhone: "region/rhone.jpg",
    sud_ouest: "region/sud.jpg",
    default: "default_wine.avif"
  }.freeze

  REGIONS = %i[
    alsace_lorraine
    beaujolais
    bordeaux
    bourgogne
    champagne
    corse
    jura_bugey_savoie
    languedoc_roussillon
    loire
    provence
    rhone
    sud_ouest
  ].freeze

  enumerize :region, in: REGIONS, predicates: true

  # Validations
  validates :region, presence: true
  validates :domaine_name, presence: true

  accepts_nested_attributes_for :producer_labels, reject_if: proc { |attributes| attributes["label_id"].blank? }

  after_create do
    cover = PHOTO[region.to_sym] || PHOTO[:default]
    update(cover:)
  end
end

app/controllers/maintenance/producers_controller.rb
# frozen_string_literal: true

module Maintenance
  class ProducersController < BaseController
    before_action :set_producer, only: %i[edit update destroy]

    def index
      @producers = Producer.all
      @breadcrumb_items = {
        "maintenance.base.index.title": maintenance_path
      }
    end

    def edit
      @breadcrumb_items = {
        "maintenance.base.index.title": maintenance_path,
        "maintenance.producers.index.title": maintenance_producers_path
      }
      @producer = Producer.find(params[:id])
    end

    def update
      @producer.update(producer_params)
      respond_to do |format|
        if @producer.save
          flash[:success] = t("update_done")
          format.html { redirect_to producer_path(@producer) }
        else
          flash[:alert] = t("update_error")
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      if @producer.bottles.empty?
        @producer.destroy
        redirect_to maintenance_producers_path
      else
        @producers = Producer.all
        flash[:notice] = t(".error")
        render :index
      end
    end

    private

    def set_producer
      @producer = Producer.includes(:labels).find(params[:id])
    end

    def producer_params
      params.require(:producer).permit(
        :latitude, :longitude,
        :address, :region,
        :domaine_name, :name,
        :website,
        { producer_labels_attributes: [:label_id] }
      )
    end
  end
end

app/controllers/producers_controller.rb
# frozen_string_literal: true

class ProducersController < ApplicationController
  before_action :set_producer, only: %i[show edit update]

  def index
    @breadcrumb_items = {
      "producers.index.feed": feed_path
    }

    if params[:search]
      @producers = Producer.where(user_id: Current.user)
      @filter = true
    else
      @producers = Producer.all
      @filter = false
    end
  end

  def show
    @breadcrumb_items = {
      "producers.show.feed": feed_path,
      "producers.show.producers": producers_path
    }
  end

  def new
    @breadcrumb_items = {
      "producers.show.feed": feed_path
    }
    @producer = Producer.new
  end

  def edit
    @breadcrumb_items = {
      "producers.edit.feed": feed_path,
      "producers.edit.producers": producers_path
    }
  end

  def create
    @producer = current_user.producers.build(producer_params)

    respond_to do |format|
      if @producer.save
        format.html { redirect_to producer_path(@producer) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @producer.update(producer_params)
    respond_to do |format|
      if @producer.save
        format.html { redirect_to producer_path(@producer) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_producer
    @producer = Producer.includes(:labels).find(params[:id])
  end

  def producer_params
    params.require(:producer).permit(
      :address,
      :domaine_name,
      :name,
      :region,
      :website,
      :latitude,
      :longitude,
      { producer_labels_attributes: [:label_id] }
    )
  end
end

app/views/producers/_form.html.slim
= simple_form_for @producer, data: {controller: "address-autocomplete", address_autocomplete_api_key_value: Rails.application.credentials.mapbox.public_key} do |f|
  = render FormComponent::FormComponent.new do |c|
    = f.hidden_field :latitude, data: { address_autocomplete_target: "latitude" }
    = f.hidden_field :longitude, data: { address_autocomplete_target: "longitude" }
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      div
        = f.hidden_field :address, placeholder: t("placeholders.address_exemple"), data: { address_autocomplete_target: "address" }
        = f.label t("placeholders.address"), class:"block text-sm font-medium text-gray-700 mb1"
        .w-full data={"address-autocomplete-target": "search"}
      = f.input :region, placeholder: t("placeholders.region")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :domaine_name, placeholder: t("placeholders.domaine_name")
      = f.input :name, placeholder: t("placeholders.producer")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :website, placeholder: t("placeholders.website")

    - if @producer.persisted?
      .w-full.flex.flex-wrap.items-end.justify-center.inline-block.gap-2.shrink-0.mb-3.md:mb-0.lg:mb-3.xl:mb-0
        - @producer.producer_labels.each do |producer_label|
          = render "producer_labels/producer_label", producer_label: producer_label

    fieldset.border.p-3.mb-6.rounded-md data-controller="nested-form"
      legend.px-2.mb-3.text-sm.font-semibold.text-gray-700 = t("placeholders.producer_labels")

      template data-nested-form-target="template"
        = f.simple_fields_for :producer_labels, ProducerLabel.new, child_index: "CHILD_INDEX" do |producer_label_form|
          = render "producer_label_fields", form: producer_label_form

      .mt-1 data-nested-form-target="associations"
        = f.simple_fields_for :producer_labels, ProducerLabel.new do |producer_label_form|
          = render "producer_label_fields", form: producer_label_form

      .mt-1
        = button_tag data: { action: "nested-form#addAssociation" }, class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none" do
          i.fa-solid.fa-plus.mr-1
          = t(".add_label")

    - c.with_action do
      = f.submit t("save"), class: "btn btn-primary"

app/views/producers/_producer_label_fields.html.slim
/ .nested-fields is needed to be deleted by Stimulus
.nested-fields
  .pt-2.flex.justify-between.items-center
    .grow.grid.grid-cols-1.gap-3.mr-8.lg:mr-4
      div
        = form.input :label_id, class: "text-input mb-6",
          label: t("option"),
          collection: Label.all, label_method: :name, value_method: :id

    .mx-3.align-self-end
      = button_tag data: { action: "nested-form#removeAssociation" } do
        i.fas.fa-trash-alt.text-danger

app/views/producers/edit.html.slim
- content_for :title do
  = t(".edit_producer")

= render "form"

app/views/producers/index.html.slim
- content_for :title do
  = t(".producers")
.bg-white
  .mx-auto.max-w-2xl.py-8.px-4.sm:py-12.sm:px-6.lg:max-w-7xl.lg:px-8 data-controller="toggle" data-toggle-class-value="hidden"
    h2.sr-only = t(".producers")
    = link_to "Tous les producteurs",
          producers_path,
          class: "btn btn-primary flex justify-center mb-2 #{'hidden' if !@filter}",
          data: { turbo_frame: "producers", "toggle-target": "content", action: "click->toggle#toggle" }
    = link_to "Mes producteurs",
      producers_path(search: "my_wines"),
      class: "btn btn-primary flex justify-center mb-2 #{'hidden' if @filter}",
      data: { turbo_frame: "producers", "toggle-target": "content", action: "click->toggle#toggle" }
    = turbo_frame_tag "producers", class:"grid grid-cols-1 gap-y-4 sm:grid-cols-2 sm:gap-x-6 sm:gap-y-10 lg:grid-cols-3 lg:gap-x-8" do
      - @producers.each do |producer|
        .flex.justify-center.p-2
          .flex.flex-col.overflow-x-hidden.overflow-y-auto.w-full.h-full
            div.overflow-hidden.p-4.md:p-6.flex.flex-col.bg-cover.bg-center.shrink-0 style='background-image: linear-gradient(180deg, rgba(0,0,0,0.6264706566220238) 0%, rgba(0,0,0,0.6404762588629201) 18%, rgba(255,255,255,0) 100%), url("#{image_path producer.cover}");'
              .flex.justify-between
                h2.grow.text-white.text-2xl.h-16.mb-4.md:mb-6.mr-5.md:mr-3.text-ellipsis.overflow-hidden title=("#{producer.domaine_name}") = producer.domaine_name
                = link_to edit_producer_path(producer) do
                  i.fa-pen-to-square.fa-duotone.fa-fw.text-red-500
              .mb-4.md:mb-6
                .mt-4.flex.flex-col.overflow-hidden.space-x-0.space-y-3
                  - if producer.name
                    = render(LabelComponent::LabelComponent.new(name: producer.name, type: "tag"))
                  = render(LabelComponent::LabelComponent.new(name: producer.region, type: "grapes"))

            div.w-full.p-4.md:p-6.bg-gray-100.flex.flex-col.justify-between.grow
              .flex.flex-col.justify-between.items-center
                - if producer.labels.any?
                  .w-full.flex.flex-wrap.items-center.justify-center.inline-block.gap-2.shrink-0.mb-3.md:mb-0.lg:mb-3.xl:mb-0
                    - producer.labels.each do |label|
                      = regular_image(label.photo, 80)
                p.text-center.w-full.inline-block.text-sm.mb-3 = producer.address
                .flex
                  - if producer.website?
                    = link_to "Voir le site du vigneron", "#{producer.website}", target: "_blank", class: "btn btn-primary py-2 px-3"
                  - else
                    = link_to "Renseigner le site", edit_producer_path(producer), target: "_blank", class: "btn btn-primary py-2 px-3"
                .flex
                  - if producer.bottles.any?
                    = link_to "Les vins du vigneron", bottles_path(query: producer.domaine_name), class: "btn btn-primary py-2 px-3 mt-4"

app/views/producers/new.html.slim
- content_for :title do
  = t(".new_producer")

= simple_form_for @producer, url: producers_path, data: {controller: "address-autocomplete", address_autocomplete_api_key_value: Rails.application.credentials.mapbox.public_key} do |f|
  = render FormComponent::FormComponent.new do |c|
    = f.hidden_field :latitude, data: { address_autocomplete_target: "latitude" }
    = f.hidden_field :longitude, data: { address_autocomplete_target: "longitude" }
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      div
        = f.hidden_field :address, placeholder: t("placeholders.address"), data: { address_autocomplete_target: "address" }
        = f.label t(".address"), class:"block text-sm font-medium text-gray-700 mb1"
        .w-full data={"address-autocomplete-target": "search"}
      = f.input :region, placeholder: t("placeholders.region")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :domaine_name, placeholder: t("placeholders.domaine_name")
      = f.input :name, placeholder: t("placeholders.producer")
    .grid.grid-cols-1.gap-y-6.gap-x-4.sm:grid-cols-2
      = f.input :website, placeholder: t("placeholders.website")

    fieldset.border.p-3.mb-6.rounded-md data={ controller: "nested-form" }
      legend.px-2.mb-3.text-sm.font-semibold.text-gray-700 = t(".producer_labels")

      template data={ target: "nested-form.template"}
        = f.simple_fields_for :producer_labels, ProducerLabel.new, child_index: "CHILD_INDEX" do |producer_label_form|
          = render "producer_label_fields", form: producer_label_form

      .mt-1 data={ target: "nested-form.associations"}
        = f.simple_fields_for :producer_labels, ProducerLabel.new do |producer_label_form|
          = render "producer_label_fields", form: producer_label_form

      .mt-1
        = button_tag data: { action: "nested-form#addAssociation" }, class: "inline-flex items-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none" do
          i.fa-solid.fa-plus.mr-1
          = t(".add_label")

    - c.with_action do
      = f.submit t("save"), class: "btn btn-primary"

app/views/producers/show.html.slim
= turbo_frame_tag "producer-show" do
  - render ProducerShowComponent::ProducerShowComponent.new(producer: @producer)